# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20170629_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phno',
            field=models.CharField(max_length=20),
        ),
    ]
